//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingStaff
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdTrainee { get; set; }
        public int IdTrainer { get; set; }
        public int IdCourse { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
